mqtt:
  host: "192.168.1.10"
  port: 1883
  username: ""
  password: ""

# Seconds between DDC/CI state reads.
interval: 20

display:
  - id: 0
    inputs:
      HDMI: 17
      DisplayPort: 15
    gamer_modes:
      Off: 0
      FPS: 11
      RTS: 12
      Racing: 13
      Gamer 1: 14
      Gamer 2: 15
      Gamer 3: 16
    color_presets:
      sRGB: 1
      Warm: 5
      Normal: 6
      Cool: 8
      User: 11
  - id: 1
    inputs:
      HDMI: 17
      DisplayPort: 15
    gamer_modes:
      Off: 0
      FPS: 11
      RTS: 12
      Racing: 13
      Gamer 1: 14
      Gamer 2: 15
      Gamer 3: 16
    color_presets:
      sRGB: 1
      Warm: 5
      Normal: 6
      Cool: 8
      User: 11
